### ISSUE TITLE
error in readme install instructions?

### ISSUE THREAD

**Issue by lukemac1** [GShotwell/easyMake#5]
This may unique to my situation, but 'Rtools' didn't work to install the package as it wasn't available for either version 3.2.2 or 3.2.3. The code 'library(Rtools)' produced an error saying there was no such package (maybe its deprecated or something?). 

I installed 'devtools', and after that had to use the command 'install_github', instead of 'install.github'. 

I'm looking forward to trying the package out!

**Comment by gshotwell** [comment]
Not unique at all, Readme has been updated. Thanks!
